# Grafana Docker Image for use with Red Hat OpenShift

This repository builds a docker image for use with Red Hat OpenShift taking into account security considerations for running on OpenShift - e.g. not running under the `root` user.

. To build:
+
[source,bash]
----
docker build . -t wkulhanek/grafana:latest
docker push wkulhanek/grafana:latest
----
+
The repository includes an OpenShift Template to run Grafana with persistent storage.

. To deploy:
+
[source,bash]
----
oc new-project grafana --display-name="Monitoring - Grafana Dashboards"
oc new-app -f grafana -p VOLUME_CAPACITY=4Gi
----

* Log into Grafana using the Route provided in the Template and using default account `admin` with password `admin` (maybe it would be a good idea to change the password after this...).

. Grafana Data Source

* The Grafana template automatically provisions a Prometheus data source `DS-Prometheus` which connects to `http://prometheus:9090` via proxy connection.
* This works if there is a Prometheus (called `prometheus`) in the same project as Grafana. If this is not the case it is necessary to edit the datasource to point to another location.

. Grafana Dashboard

* The Grafana template automatically provisions a rudimentary OpenShift metrics dashboard. This dashboard is by no means comprehensive but could be used as a starting point for further customization.
* The configured dashboard depends on metrics that are being collected by Prometheus as configured in https://github.com/wkulhanek/openshift-prometheus.

* There are more example dashboards available at https://grafana.com/dashboards?search=kubernetes.
