# Grafana Docker Image for use with Red Hat OpenShift

This repository builds a docker image for use with Red Hat OpenShift taking into account security considerations for running on OpenShift - e.g. not running under the `root` user.

This container image supports installation of custom Grafana plugins (data sources, panels, apps) from https://grafana.com/plugins. To install during the build process download the plugin zip file and place it into root/var/lib/grafana-plugins before building the image.

. To build:
+
[source,bash]
----
docker build . -t wkulhanek/grafana:latest
docker push wkulhanek/grafana:latest
----
+
The repository includes an OpenShift Template to run Grafana with persistent storage.

. To deploy:
+
[source,bash]
----
oc new-project grafana --display-name="Monitoring - Grafana Dashboards"
oc create -f grafana.yaml
oc new-app grafana -p NAMESPACE=grafana -p VOLUME_CAPACITY=4Gi
----

. Configure a Grafana Data Source

* Log into Grafana using the Route provided in the Template and using default account `admin` with password `admin` (maybe it would be a good idea to change the password after this...).
* On the Home Dashboard click *Add data source*
* Use the following values for the datasource *Config*:
** Name: `DS-Prometheus`
** Type: `Prometheus`
** Url: Route to your prometheus *without* a trailing `/`. E.g. `http://prometheus-prometheus.apps.127.0.0.1.nip.io`
** Access: direct
* Click `Add`
* Click `Save & Test`. You should see a message that the data source is working.

. Configure a Grafana Dashboard

* There is an example dashboard JSON file `openshift-metrics-dashboard.json` available in the repository. This dashboard depends on metrics that are being collected by Prometheus as configured in https://github.com/wkulhanek/openshift-prometheus.
** There are more example dashboards available at https://grafana.com/dashboards?search=kubernetes.
* In Grafana select the Icon on the top left and then select `Dashboards / Import`.
* Either copy/paste the contents of the JSON File (make sure to keep the correct formatting) or click the `Upload .json File` button selecting the .json file.
* In the next dialog enter `OpenShift` as the name and select the previously created datasource `DS-Prometheus` for *Prometheus*.
* Click *Import*
